volumes:
  portainerdata:

networks:
  network-zabbix:
    driver: bridge

services:
  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - network-zabbix
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000